# Generated by Django 6.0.5 on 2026-05-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_payment_booking_remove_event_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
